# 开发案例



## 知识准备

1.SDK       

2.github   

3.gitee   





### 软件

git













## 管道开发案例

```c#
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.UI.Selection;
using BinLibrary;
using BinLibrary.RevitExtension;
using Autodesk.Revit.DB.Plumbing;
 
namespace RevitRebuild
{
    
    [Regeneration(RegenerationOption.Manual)]
    [Journaling(JournalingMode.UsingCommandData)]
    [Transaction(TransactionMode.Manual)]
    class Cmd_PipeParallel : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
 
            var app = commandData.Application;
            var uidoc = app.ActiveUIDocument;
            var doc = uidoc.Document;
            var selection = uidoc.Selection;
 
            var acview = doc.ActiveView;
 
 
            var eleref1 = selection.PickObject(ObjectType.Element);
 
            var element1 = doc.GetElement(eleref1);
 
 
 
            var elerefs1 = selection.PickObjects(ObjectType.Element);
 
            var elements1 = elerefs1.Select(m => m.GetElement(doc)).ToList();
 
 
            var pipe1 = element1 as Pipe;
 
            var line1 = (pipe1.Location as LocationCurve).Curve as Line;
 
            var startpo = line1.GetEndPoint(0);
            var endpo = line1.GetEndPoint(1);
 
            var dir = (endpo - startpo).Normalize();
 
            Transaction ts = new Transaction(doc);
 
            ts.Start("aaa");
 
            foreach (var ele in elements1)
            {
                var pipe = ele as Pipe;
 
                var ppll = pipe.LocationLine();
 
                var length = ppll.Length;
 
                var startll = ppll.StartPoint();
 
                var endll = startll + dir * (length);
 
                var newll = Line.CreateBound(startll, endll);
 
 
                (pipe.Location as LocationCurve).Curve = newll;
 
 
            }
 
 
 
            ts.Commit();
             
             
            return Result.Succeeded;
        }
    }
}
```





## 开发流程 



